// <auto-generated />
using Database.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Database.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20220109222959_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("Database.Models.Monster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("ArmorClass")
                        .HasColumnType("integer");

                    b.Property<int>("AttackModifer")
                        .HasColumnType("integer");

                    b.Property<int>("AttackPerRound")
                        .HasColumnType("integer");

                    b.Property<int>("Damage")
                        .HasColumnType("integer");

                    b.Property<int>("DamageModifer")
                        .HasColumnType("integer");

                    b.Property<int>("HitPoints")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("Weapon")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Monsters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArmorClass = 16,
                            AttackModifer = 8,
                            AttackPerRound = 1,
                            Damage = 4,
                            DamageModifer = 3,
                            HitPoints = 80,
                            Name = "Titan of dawn",
                            Weapon = 0
                        },
                        new
                        {
                            Id = 2,
                            ArmorClass = 10,
                            AttackModifer = 2,
                            AttackPerRound = 1,
                            Damage = 1,
                            DamageModifer = 1,
                            HitPoints = 13,
                            Name = "Elk",
                            Weapon = 1
                        },
                        new
                        {
                            Id = 3,
                            ArmorClass = 17,
                            AttackModifer = 10,
                            AttackPerRound = 3,
                            Damage = 3,
                            DamageModifer = 2,
                            HitPoints = 105,
                            Name = "Orthon",
                            Weapon = 3
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
